{% set name = "dataframe_image" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dexplo/dataframe_image/archive/v{{ version }}.tar.gz
  sha256: 6d96368cbf64e8291587242bd6442ed2961cc021a06d2ccf1d309fe460e77831

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - dataframe_image=dataframe_image._command_line:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # nbconvert is not available for py313
  skip: True  # [py<38 or py>312]
  # playwright-python is not available on s390x
  skip: True  # [s390x]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
    - setuptools_scm
  run:
    - python
    - pandas >=0.24
    - nbconvert >=5
    - aiohttp >=3.10.2
    - requests
    - pillow
    - packaging
    - mistune
    - lxml
    - beautifulsoup4
    - cssutils
    - playwright-python
    - cssselect

test:
  source_files:
    - pytest.ini
    - tests
    - dataframe_image
  imports:
    - dataframe_image
  commands:
    - pip check
    - dataframe_image --help
    - playwright install chromium  # [py<313]
    - pytest -v tests  # [py<313]
  requires:
    - pip
    - pytest >=8.0.2,<9.0.0
    - pytest-asyncio >=0.23.6,<0.24.0
    - matplotlib-base
    - selenium  # [py<313]
    - jupyter  # [py<313]
    # To avoid OSError("Chrome executable not able to be found on your machine")
    # https://github.com/dexplo/dataframe_image/issues/6
    - python-chromedriver-binary  # [osx and arm64]

about:
  home: https://github.com/dexplo/dataframe_image
  summary: Embed pandas DataFrames as images in pdf and markdown files when converting from Jupyter Notebooks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  desciption: |
    A package to convert pandas DataFrames as images.
    Also convert Jupyter Notebooks to PDF and/or Markdown embedding dataframe as image into it.
  dev_url: https://github.com/dexplo/dataframe_image
  doc_url: https://dexplo.org/dataframe_image

extra:
  recipe-maintainers:
    - tdpetrou
